Refactor part of the script

diff --git a/bin/restoredbora b/bin/restoredbora
--- a/bin/restoredbora
+++ b/bin/restoredbora
@@ -41,22 +41,40 @@ readonly ADMINROOT="D:\app\f.niessen\admin\\$HOSTSTRING"
 AFM_SECURE_SCHEMA="${AFM_SCHEMA}_SECURE"
 
 # Check for Data Pump file.
-if [[ ! -f "$ADMINROOT"/dpdump/"$DATA_PUMP_FILE" ]]; then
-    echo "ERROR: Data Pump file $ADMINROOT/dpdump/$DATA_PUMP_FILE not found" >&2
-    exit 2
-fi
+check_file_exists() {
+    local file_path="$ADMINROOT/dpdump/$DATA_PUMP_FILE"
+    if [[ ! -f "$file_path" ]]; then
+        echo "ERROR: Data Pump file $file_path not found" >&2
+        exit 2
+    fi
+}
+
+# Check the length of the AFM schema name.
+check_afm_schema_length() {
+    local afm_schema=$1
+    if [[ ${#afm_schema} -gt 23 ]]; then
+        echo "ERROR: AFM schema name $afm_schema is longer than 23 characters" >&2
+        exit 2
+    fi
+}
 
 # Confirm action.
-echo "Data Pump File:      $DATA_PUMP_FILE"
-echo "AFM Schema:          $AFM_SCHEMA"
-echo "AFM_SECURE Schema:   $AFM_SECURE_SCHEMA"
-echo "@Database:           $HOSTSTRING"
+confirm_action() {
+    echo "Data Pump File:     $DATA_PUMP_FILE"
+    echo "AFM Schema:         $AFM_SCHEMA"
+    echo "AFM_SECURE Schema:  $AFM_SECURE_SCHEMA"
+    echo "@Database:          $HOSTSTRING"
 
-read -p "Are you sure? " -n 1 -r
-echo                                    # Move to a new line.
-if [[ ! $REPLY =~ ^[Yy]$ ]]; then
-    exit 1
-fi
+    read -p "Are you sure? " -n 1 -r
+    echo
+    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
+        exit 2
+    fi
+}
+
+check_file_exists
+check_afm_schema_length "$AFM_SCHEMA"
+confirm_action
 
 # 1.
 printf '\nINFO- Before impdp...\n'
